default_thresholds: &default_thresholds
  memory:
    max:
      error: 100%
      warning: 95%
      problem: 90%
    max_rss:
      error: 95%
      warning: 90%
      problem: 85%
    average:
      error: 90%
      warning: 85%
      problem: 80%
  responseTime:
    p95:
      error: 1200
      warning: 1000
      problem: 900
    median:
      error: 750
      warning: 550
      problem: 500
  responseStatus:
    5XX:
      error: 5
      warning: 2
      problem: 1
  errorCode:
    error: [H10, H14]
    warning: [H12, H19, H21]
    ok: [H27]
